name: tambalbanonline
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.2.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.6
  flutter: 
    sdk: flutter
  firebase_auth: ^4.17.8
  firebase_core: ^2.27.0
  shared_preferences: ^2.2.3
  gap: ^3.0.1
  shimmer: ^3.0.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  map_launcher: ^3.3.0
  geolocator: ^11.0.0
  permission_handler: ^11.3.1
  firebase_storage: ^11.6.9
  image_picker: ^1.0.8
  cloud_firestore: ^4.15.8
  google_maps_flutter: ^2.5.3
  latlng: ^2.0.7

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/

